# Generated by Django 6.0.1 on 2026-01-21 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('sistemas', 'Sistemas'), ('calidad', 'Calidad'), ('datos', 'Datos'), ('analista', 'Analista')], default='analista', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('creado', 'Creado (Pendiente)'), ('protocolo_cargado', 'Protocolo Cargado'), ('hoja_cargada', 'Hoja de Cálculo Cargada (En Revisión)'), ('cerrado', 'Cerrado / Finalizado')], default='creado', max_length=30)),
                ('archivo_protocolo', models.FileField(blank=True, null=True, upload_to='protocolos/')),
                ('fecha_subida_protocolo', models.DateTimeField(blank=True, null=True)),
                ('archivo_hoja_calculo', models.FileField(blank=True, null=True, upload_to='hojas/')),
                ('fecha_subida_hoja', models.DateTimeField(blank=True, null=True)),
                ('datos_protocolo', models.JSONField(blank=True, default=dict)),
                ('datos_hoja_calculo', models.JSONField(blank=True, default=dict)),
                ('comentarios_calidad', models.TextField(blank=True, null=True)),
                ('analista_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
