# Generated by Django 6.0.1 on 2026-01-21 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='datos_hoja_calculo',
            new_name='datos_estudio',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='datos_protocolo',
            new_name='datos_validacion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='analista_asignado',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='archivo_hoja_calculo',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='archivo_protocolo',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='comentarios_calidad',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_subida_hoja',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_subida_protocolo',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('analista', 'Analista'), ('calidad', 'Revisor Calidad'), ('sistemas', 'Administrador de Sistemas')], default='calidad', max_length=20),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En Proceso'), ('terminado', 'Terminado')], default='en_proceso', max_length=20),
        ),
    ]
