# Generated by Django 6.0.1 on 2026-01-22 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_user_perfil_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_subida_firmado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='informe_final_firmado',
            field=models.FileField(blank=True, null=True, upload_to='informes_firmados/'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nombre_analista',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Analista Asignado'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En Proceso'), ('terminado', 'Terminado (Histórico)')], default='en_proceso', max_length=20),
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='core.proyecto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
