# Generated by Django 6.0.1 on 2026-02-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_proyecto_fecha_subida_firmado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroactividad',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
